# Generated by Django 3.0.5 on 2020-04-30 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_genre_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(to='blog.Genre'),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Publisher'),
        ),
    ]
